<?php

/*
 * Xibo - Digital Signage - http://www.xibo.org.uk
 *
 * This file is part of Xibo - and is automatically generated by the installer
 *
 * You should not need to edit this file, unless your SQL connection details have changed.
 */

defined('XIBO') or die(__("Sorry, you are not allowed to directly access this page.") . "<br />" . __("Please press the back button in your browser."));

global $dbhost;
global $dbuser;
global $dbpass;
global $dbname;

$dbhost = 'localhost';
$dbuser = 'root';
$dbpass = '';
$dbname = 'xibo';

define('SECRET_KEY', '136Tt29zEuM9');

// Additional Monolog handlers/processors to be registered
// $logHandlers = [];
// $logProcessors = [];

// Additional Middleware
// $middleware = [];
// $authentication = ;
